### ISSUE TITLE
h5py is running against HDF5 1.12.1 when it was built against 1.12.2

### ISSUE THREAD

**Issue by michaelosthege** [conda-forge/h5py-feedstock#122]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

We ran into the well-known "h5py is running against HDF5 x when it was built against y" issue.

We could circumvent it by pinning to an ealier `h5py` version: `mamba install -c conda-forge "h5py=3.6.0"`.

Interestingly the error is conditional on the order of imports.

Doing just `import h5py` results in

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\dibecs_6.2.2\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\dibecs_6.2.2\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: Die angegebene Prozedur wurde nicht gefunden.
```

But doing `python -c "import arviz;import h5py"` gives the error below.

I have a feeling that this might be an incompatibility with NetCDF4.

```
C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\dibecs_6.2.2\lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.12.1 when it was built against 1.12.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.2, library is 1.12.1
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.12.1
                  Configured on: 2022-03-04
                  Configured by: Ninja
                    Host system: Windows-10.0.17763
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: D:/bld/hdf5_split_1646412547396/_h_env/Library

Compiling Options:
------------------
                     Build Mode: RELEASE
              Debugging Symbols: OFF
                        Asserts: OFF
                      Profiling: OFF
             Optimization Level: OFF

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libcurl.lib;D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libssl.lib;D:/bld/hdf5_split_1646412547396/_h_env/Library/lib/libcrypto.lib
                       Archiver: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/lib.exe
                         Ranlib: :

Languages:
----------
                              C: YES
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe 19.16.27045.0
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:   /DWIN32 /D_WINDOWS
                      H5_CFLAGS: /W3;/wd4100;/wd4706;/wd4127
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/cl.exe 19.16.27045.0
                      C++ Flags:
                   H5 C++ Flags: /W3;/wd4100;/wd4706;/wd4127
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                 JAVA Compiler:

Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                Build HDF5 Tests: ON
                Build HDF5 Tools: ON
                    Threadsafety: ON (recursive RW locks: )
             Default API mapping: v112
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE
                             MPE:
                      Direct VFD:
                      Mirror VFD:
              (Read-Only) S3 VFD: 1
            (Read-Only) HDFS VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
                Use file locking: best-effort
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...
```

### Installed packages

```shell
aeppl                     0.0.35                   pypi_0    pypi
aesara                    2.8.2                    pypi_0    pypi
aiobotocore               2.4.0                    pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aioitertools              0.10.0                   pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arviz                     0.12.1                   pypi_0    pypi
astroid                   2.12.9           py38haa244fe_0    conda-forge
asttokens                 2.0.8                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
black                     22.8.0           py38haa244fe_0    conda-forge
bleach                    5.0.1                    pypi_0    pypi
botocore                  1.27.74                  pypi_0    pypi
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.9.14            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0                    pypi_0    pypi
cairo                     1.16.0            hd694305_1013    conda-forge
certifi                   2022.9.14          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1                   pypi_0    pypi
cfgv                      3.3.1                    pypi_0    pypi
cftime                    1.6.1                    pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3            py38haa244fe_0    conda-forge
cloudpickle               2.2.0                    pypi_0    pypi
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
cons                      0.4.5                    pypi_0    pypi
coverage                  6.4.4            py38h294d835_0    conda-forge
csaps                     1.1.0                    pypi_0    pypi
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dask                      2022.9.0                 pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.5.1            pyhd8ed1ab_0    conda-forge
distlib                   0.3.6                    pypi_0    pypi
distributed               2022.9.0                 pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
etuples                   0.3.8                    pypi_0    pypi
executing                 1.0.0                    pypi_0    pypi
expat                     2.4.8                h39d44d4_0    conda-forge
fastjsonschema            2.16.1                   pypi_0    pypi
fastprogress              1.0.3                    pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.37.2           py38h91455d4_0    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.8.2                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  6.0.1                h8f5d4a1_0    conda-forge
gst-plugins-base          1.20.3               h001b923_1    conda-forge
gstreamer                 1.20.3               h6b5321d_1    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
h5py                      3.7.0           nompi_py38h35e7eba_101    conda-forge
hagelkorn                 1.2.3                    pypi_0    pypi
harfbuzz                  5.1.0                h27de254_0    conda-forge
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
heapdict                  1.0.1                    pypi_0    pypi
icu                       70.1                 h0e60522_0    conda-forge
identify                  2.5.5                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.21.3                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
importlib-metadata        4.12.0                   pypi_0    pypi
importlib-resources       5.9.0                    pypi_0    pypi
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipykernel                 6.15.3                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
jsonpickle                2.2.0                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
kiwisolver                1.4.4            py38hbd9d945_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lazy-object-proxy         1.7.1            py38h294d835_1    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libcurl                   7.83.1               h789b8ee_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgd                     2.3.3                h891f43f_3    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_4    conda-forge
libpython                 2.2              py38haa244fe_1    conda-forge
libsqlite                 3.39.3               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                h8e97e67_4    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.4                h8ffe710_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               hcfcfb64_3    conda-forge
llvmlite                  0.38.1           py38h57a6900_0    conda-forge
locket                    1.0.0                    pypi_0    pypi
logical-unification       0.4.5                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
m2w64-binutils            2.25.1                        5    conda-forge
m2w64-bzip2               1.0.6                         6    conda-forge
m2w64-crt-git             5.0.0.4636.2595836               2    conda-forge
m2w64-gcc                 5.3.0                         6    conda-forge
m2w64-gcc-ada             5.3.0                         6    conda-forge
m2w64-gcc-fortran         5.3.0                         6    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gcc-objc            5.3.0                         6    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-headers-git         5.0.0.4636.c0ad18a               2    conda-forge
m2w64-isl                 0.16.1                        2    conda-forge
m2w64-libiconv            1.14                          6    conda-forge
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
m2w64-make                4.1.2351.a80a8b8               2    conda-forge
m2w64-mpc                 1.0.3                         3    conda-forge
m2w64-mpfr                3.1.4                         4    conda-forge
m2w64-pkg-config          0.29.1                        2    conda-forge
m2w64-toolchain           5.3.0                         7    conda-forge
m2w64-tools-git           5.0.0.4592.90b8472               2    conda-forge
m2w64-windows-default-manifest 6.4                           3    conda-forge
m2w64-winpthreads-git     5.0.0.4634.697f757               2    conda-forge
m2w64-zlib                1.2.8                        10    conda-forge
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.3            py38haa244fe_2    conda-forge
matplotlib-base           3.5.3            py38h3268a40_2    conda-forge
matplotlib-inline         0.1.6                    pypi_0    pypi
matrixprofile             1.1.10                   pypi_0    pypi
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
minikanren                1.0.3                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-service               2.4.0            py38hb96a4b1_0    conda-forge
msgpack                   1.0.4                    pypi_0    pypi
msys2-conda-epoch         20160418                      1    conda-forge
multidict                 6.0.2                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      0.971            py38h294d835_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_5    conda-forge
nbclient                  0.6.8                    pypi_0    pypi
nbconvert                 7.0.0                    pypi_0    pypi
nbformat                  5.5.0                    pypi_0    pypi
nest-asyncio              1.5.5                    pypi_0    pypi
netcdf4                   1.6.1                    pypi_0    pypi
nodeenv                   1.7.0                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
numba                     0.55.2           py38h860efb6_0    conda-forge
numpy                     1.22.4           py38h1d2777f_0    conda-forge
omero-py                  5.12.0                   pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.10                   pypi_0    pypi
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
paho-mqtt                 1.6.1                    pypi_0    pypi
pandas                    1.4.4            py38h0ae2778_0    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
pango                     1.50.9               h480d202_0    conda-forge
parso                     0.8.3                    pypi_0    pypi
partd                     1.3.0                    pypi_0    pypi
pathspec                  0.10.1             pyhd8ed1ab_0    conda-forge
patsy                     0.5.2                    pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py38h37aa274_2    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.2              pyhd8ed1ab_1    conda-forge
pluggy                    1.0.0            py38haa244fe_3    conda-forge
ply                       3.11                       py_1    conda-forge
pre-commit                2.20.0                   pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
protobuf                  3.11.2                   pypi_0    pypi
psutil                    5.9.2            py38h91455d4_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure-eval                 0.2.2                    pypi_0    pypi
py                        1.11.0             pyh6c4a22f_0    conda-forge
pycparser                 2.21                     pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pylint                    2.15.2             pyhd8ed1ab_0    conda-forge
pymc                      4.1.7                    pypi_0    pypi
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py38h75e37d8_0    conda-forge
pyqt5-sip                 12.11.0          py38h885f38d_0    conda-forge
pyrff                     2.0.2                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pytest                    7.1.3            py38haa244fe_0    conda-forge
pytest-cov                3.0.0              pyhd8ed1ab_0    conda-forge
python                    3.8.13          h9a09f29_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-graphviz           0.20.1             pyh22cad53_0    conda-forge
python-logging-loki       0.3.1                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pythonnet                 2.5.2                    pypi_0    pypi
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pywin32                   304                      pypi_0    pypi
pywinpty                  2.0.8                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.0                   pypi_0    pypi
qt-main                   5.15.6               hf0cf448_0    conda-forge
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.0                    pypi_0    pypi
requests                  2.28.1                   pypi_0    pypi
rfc3339                   6.2                      pypi_0    pypi
robotools                 1.3.0                    pypi_0    pypi
s3fs                      2022.8.2                 pypi_0    pypi
s3transfer                0.6.0                    pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.1            py38h91810f7_0    conda-forge
seaborn                   0.12.0                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.3.0             pyhd8ed1ab_1    conda-forge
sip                       6.6.2            py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slack-sdk                 3.18.3                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.3               hcfcfb64_0    conda-forge
stack-data                0.5.0                    pypi_0    pypi
statsmodels               0.13.2                   pypi_0    pypi
stumpy                    1.11.1                   pypi_0    pypi
tbb                       2021.5.0             h91493d7_2    conda-forge
tblib                     1.7.0                    pypi_0    pypi
terminado                 0.15.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.11.4             pyha770c72_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
tsfresh                   0.19.0                   pypi_0    pypi
typing                    3.7.4.3                  pypi_0    pypi
typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
typing_extensions         4.3.0              pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py38h294d835_1    conda-forge
urllib3                   1.26.12                  pypi_0    pypi
vc                        14.2                 hb210afc_7    conda-forge
virtualenv                20.16.5                  pypi_0    pypi
vs2015_runtime            14.29.30139          h890b9b1_7    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3                    pypi_0    pypi
wrapt                     1.14.1           py38h294d835_0    conda-forge
xarray                    2022.6.0                 pypi_0    pypi
xarray-einstats           0.3.0                    pypi_0    pypi
xlrd                      2.0.1                    pypi_0    pypi
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_1    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1002    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yarl                      1.8.1                    pypi_0    pypi
zeroc-ice                 3.6.5            py38hb9ab681_4    conda-forge
zict                      2.2.0                    pypi_0    pypi
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               hcfcfb64_3    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge
```

### Environment info

```shell
active environment : dibecs_6.2.2
    active env location : C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs\dibecs_6.2.2
            shell level : 1
       user config file : C:\Users\osthege\.condarc
 populated config files : C:\Users\osthege\.condarc
          conda version : 4.12.0
    conda-build version : 3.10.9
         python version : 3.7.2.final.0
       virtual packages : __cuda=11.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\osthege\AppData\Local\Continuum\miniconda3  (writable)
      conda av data dir : C:\Users\osthege\AppData\Local\Continuum\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\osthege\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\osthege\.conda\pkgs
                          C:\Users\osthege\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\osthege\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\osthege\.conda\envs
                          C:\Users\osthege\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.2 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by xylar** [comment]
I'm seeing this warning but now with 1.14.2 and 1.14.3

Update: seemingly not quite the same as above, because it's just a warning:
```
/gpfs/fs1/home/ac.xylar/chrysalis/mambaforge/envs/compass_rrs/lib/python3.10/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
```
Still, kind of annoying!

**Comment by jonsedar** [comment]
I'm getting the same error on `mdl.idata.to_netcdf(filename))` Seems to be related to `arviz`

```
UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
```

```
Python implementation: CPython
Python version       : 3.10.13
IPython version      : 8.18.1

pymc    : 5.9.2
pytensor: 2.17.3

Compiler    : Clang 16.0.6 
OS          : Darwin
Release     : 23.1.0
Machine     : arm64
Processor   : arm
CPU cores   : 8
Architecture: 64bit

sys       : 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
pandas    : 2.1.4
seaborn   : 0.12.2
oreum_core: 0.7.0
arviz     : 0.16.1
numpy     : 1.25.2
```

**Comment by tdegeus** [comment]
Same here 
```
/Users/tdegeus/miniforge3/envs/code_epm/lib/python3.12/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.14.3 when it was built against 1.14.2, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
```
I guess that version pinning is not working well?
