### ISSUE TITLE
h5py in Mac OS X Newly installed Python 3.6 cannot load libhdf5.10.dylib

### ISSUE THREAD

**Issue by jjchan121** [conda-forge/h5py-feedstock#25]
A recent installed Python 3.6 Ananconda, after I called, I have the following error.

```
python -c "import h5py"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jchan/anaconda/lib/python3.6/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: dlopen(/Users/jchan/anaconda/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/jchan/anaconda/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so
  Reason: Incompatible library version: _errors.cpython-36m-darwin.so requires version 13.0.0 or later, but libhdf5.10.dylib provides version 12.0.0
```

The following is my conda list

```
_license                  1.1                      py36_1  
alabaster                 0.7.10                   py36_0  
anaconda                  custom                   py36_0  
anaconda-client           1.6.3                    py36_0  
anaconda-navigator        1.6.2                    py36_0  
anaconda-project          0.6.0                    py36_0  
appnope                   0.1.0                    py36_0  
appscript                 1.0.1                    py36_0  
asn1crypto                0.22.0                   py36_0  
astroid                   1.4.9                    py36_0  
astropy                   1.3.2               np112py36_0  
babel                     2.4.0                    py36_0  
backports                 1.0                      py36_0  
beautifulsoup4            4.6.0                    py36_0  
bitarray                  0.8.1                    py36_0  
blaze                     0.10.1                   py36_0  
bleach                    1.5.0                    py36_0  
bokeh                     0.12.5                   py36_1  
boto                      2.46.1                   py36_0  
bottleneck                1.2.1               np112py36_0  
bzip2                     1.0.6                         1    conda-forge
cffi                      1.10.0                   py36_0  
chardet                   3.0.3                    py36_0  
click                     6.7                      py36_0  
cloudpickle               0.2.2                    py36_0  
clyent                    1.2.2                    py36_0  
colorama                  0.3.9                    py36_0  
conda                     4.3.22                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
contextlib2               0.5.5                    py36_0  
cryptography              1.8.1                    py36_0  
curl                      7.52.1                        0  
cycler                    0.10.0                   py36_0  
cython                    0.25.2                   py36_0  
cytoolz                   0.8.2                    py36_0  
dask                      0.14.3                   py36_1  
datashape                 0.5.4                    py36_0  
decorator                 4.0.11                   py36_0  
distributed               1.16.3                   py36_0  
docutils                  0.13.1                   py36_0  
entrypoints               0.2.2                    py36_1  
et_xmlfile                1.0.1                    py36_0  
fastcache                 1.0.2                    py36_1  
flask                     0.12.2                   py36_0  
flask-cors                3.0.2                    py36_0  
freetype                  2.5.5                         2  
get_terminal_size         1.0.0                    py36_0  
gevent                    1.2.1                    py36_0  
greenlet                  0.4.12                   py36_0  
h5py                      2.7.0               np112py36_1    conda-forge
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py36_1  
html5lib                  0.999                    py36_0  
icu                       54.1                          0  
idna                      2.5                      py36_0  
imagesize                 0.7.1                    py36_0  
ipykernel                 4.6.1                    py36_0  
ipython                   5.3.0                    py36_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                6.0.0                    py36_0  
isort                     4.2.5                    py36_0  
itsdangerous              0.24                     py36_0  
jbig                      2.1                           0  
jdcal                     1.3                      py36_0  
jedi                      0.10.2                   py36_2  
jinja2                    2.9.6                    py36_0  
jpeg                      9b                            0  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_3  
jupyter_client            5.0.1                    py36_0  
jupyter_console           5.1.0                    py36_0  
jupyter_core              4.3.0                    py36_0  
lazy-object-proxy         1.2.2                    py36_0  
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          0  
libpng                    1.6.27                        0  
libtiff                   4.0.6                         3  
libxml2                   2.9.4                         0  
libxslt                   1.1.29                        0  
llvmlite                  0.18.0                   py36_0  
locket                    0.2.0                    py36_1  
lxml                      3.7.3                    py36_0  
markupsafe                0.23                     py36_2  
matplotlib                2.0.2               np112py36_0  
mistune                   0.7.4                    py36_0  
mkl                       2017.0.1                      0  
mkl-service               1.1.2                    py36_3  
mpmath                    0.19                     py36_1  
msgpack-python            0.4.8                    py36_0  
multipledispatch          0.4.9                    py36_0  
navigator-updater         0.1.0                    py36_0  
nbconvert                 5.1.1                    py36_0  
nbformat                  4.3.0                    py36_0  
networkx                  1.11                     py36_0  
nltk                      3.2.3                    py36_0  
nose                      1.3.7                    py36_1  
notebook                  5.0.0                    py36_0  
numba                     0.33.0              np112py36_0  
numexpr                   2.6.2               np112py36_0  
numpy                     1.12.1                   py36_0  
numpydoc                  0.6.0                    py36_0  
odo                       0.5.0                    py36_1  
olefile                   0.44                     py36_0  
openpyxl                  2.4.7                    py36_0  
openssl                   1.0.2l                        0  
packaging                 16.8                     py36_0  
pandas                    0.20.1              np112py36_0  
pandocfilters             1.4.1                    py36_0  
partd                     0.3.8                    py36_0  
path.py                   10.3.1                   py36_0  
pathlib2                  2.2.1                    py36_0  
patsy                     0.4.1                    py36_0  
pep8                      1.7.0                    py36_0  
pexpect                   4.2.1                    py36_0  
pickleshare               0.7.4                    py36_0  
pillow                    4.1.1                    py36_0  
pip                       9.0.1                    py36_1  
ply                       3.10                     py36_0  
prompt_toolkit            1.0.14                   py36_0  
psutil                    5.2.2                    py36_0  
ptyprocess                0.5.1                    py36_0  
py                        1.4.33                   py36_0  
pycosat                   0.6.2                    py36_0  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_6  
pycurl                    7.43.0                   py36_2  
pyflakes                  1.5.0                    py36_0  
pygments                  2.2.0                    py36_0  
pylint                    1.6.4                    py36_1  
pyodbc                    4.0.16                   py36_0  
pyopenssl                 17.0.0                   py36_0  
pyparsing                 2.1.4                    py36_0  
pyqt                      5.6.0                    py36_1  
pytables                  3.4.2               np112py36_1    conda-forge
pytest                    3.0.7                    py36_0  
python                    3.6.1                         2  
python-dateutil           2.6.0                    py36_0  
python.app                1.2                      py36_4  
pytz                      2017.2                   py36_0  
pywavelets                0.5.2               np112py36_0  
pyyaml                    3.12                     py36_0  
pyzmq                     16.0.2                   py36_0  
qt                        5.6.2                         2  
qtawesome                 0.4.4                    py36_0  
qtconsole                 4.3.0                    py36_0  
qtpy                      1.2.1                    py36_0  
readline                  6.2                           2  
requests                  2.14.2                   py36_0  
rope                      0.9.4                    py36_1  
ruamel_yaml               0.11.14                  py36_1  
scikit-image              0.13.0              np112py36_0  
scikit-learn              0.18.1              np112py36_1  
scipy                     0.19.0              np112py36_0  
seaborn                   0.7.1                    py36_0  
setuptools                27.2.0                   py36_0  
simplegeneric             0.8.1                    py36_1  
singledispatch            3.4.0.3                  py36_0  
sip                       4.18                     py36_0  
six                       1.10.0                   py36_0  
snowballstemmer           1.2.1                    py36_0  
sortedcollections         0.5.3                    py36_0  
sortedcontainers          1.5.7                    py36_0  
sphinx                    1.5.6                    py36_0  
spyder                    3.1.4                    py36_0  
sqlalchemy                1.1.9                    py36_0  
sqlite                    3.13.0                        0  
statsmodels               0.8.0               np112py36_0  
sympy                     1.0                      py36_0  
tblib                     1.3.2                    py36_0  
terminado                 0.6                      py36_0  
testpath                  0.3                      py36_0  
tk                        8.5.18                        0  
toolz                     0.8.2                    py36_0  
tornado                   4.5.1                    py36_0  
traitlets                 4.3.2                    py36_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.4                         0  
wcwidth                   0.1.7                    py36_0  
werkzeug                  0.12.2                   py36_0  
wheel                     0.29.0                   py36_0  
widgetsnbextension        2.0.0                    py36_0  
wrapt                     1.10.10                  py36_0  
xlrd                      1.0.0                    py36_0  
xlsxwriter                0.9.6                    py36_0  
xlwings                   0.10.4                   py36_0  
xlwt                      1.2.0                    py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zict                      0.1.2                    py36_0  
zlib                      1.2.8                         3  
```

**Comment by kmuehlbauer** [comment]
Could be related to working in root environment and with channel mix. Try to create a dedicated conda environment and install all needed packages into this environment.

**Comment by jjchan121** [comment]
thanks kmuehlbauer for your prompt reply.

So I just created an env like one of the comment in "Cannot install certain packages after h5py without breaking h5py #5"

```
conda create --name TEST --yes --channel conda-forge python=3 numpy scipy matplotlib jupyter h5py
source activate TEST
python -c "import h5py"
```
I still have the same error unfortunately.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jchan/anaconda/envs/TEST/lib/python3.6/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: dlopen(/Users/jchan/anaconda/envs/TEST/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/jchan/anaconda/envs/TEST/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so
  Reason: Incompatible library version: _errors.cpython-36m-darwin.so requires version 13.0.0 or later, but libhdf5.10.dylib provides version 12.0.0
```

To clarify, I am using macOS Sierra, with a newly installed Ananconda 4.4.0, Python 3.6.

**Comment by kmuehlbauer** [comment]
Can you do a 'conda list' in your new environment, just to be sure all packages are from conda-forge.

**Comment by jjchan121** [comment]
```
(TEST) jchans-computer:~ jchan$ conda list
# packages in environment at /Users/jchan/anaconda/envs/TEST:
#
appnope                   0.1.0                    py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.10                       3    conda-forge
decorator                 4.1.1                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.2.1                         0    conda-forge
freetype                  2.7                           1    conda-forge
h5py                      2.7.0               np113py36_1    conda-forge
hdf5                      1.8.18                        0    conda-forge
icu                       58.1                          1    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.1.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py36_0    conda-forge
jupyter                   1.0.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
libgfortran               3.0.0                         0    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2               np113py36_0    conda-forge
mistune                   0.7.4                    py36_0    conda-forge
nbconvert                 4.2.0                    py36_0  
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.0.0                    py36_0    conda-forge
numpy                     1.13.1          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.0.2l                        0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
prompt_toolkit            1.0.14                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        5.6.2                         1    conda-forge
qtconsole                 4.3.0                    py36_0    conda-forge
readline                  6.2                           0    conda-forge
scipy                     0.19.1          np113py36_blas_openblas_200  [blas_openblas]  conda-forge
setuptools                33.1.1                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.6                      py36_0    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
xz                        5.2.2                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by kmuehlbauer** [comment]
@jjchan121 I do not see any obvious there, besides that 'nbconvert' is missing the conda-forge. Can someone with access to a Mac check this? @jakirkham Do you have any thoughts on this?

**Comment by jakirkham** [comment]
Not at the moment. Am swamped with other work.

Though from a quick glance nothing stands out to me. Also am not able to reproduce in Python 2.7 with NumPy 1.13, Python 3.6 with NumPy 1.13 (or 1.12, which the user had before).

Some questions for info for later. Are you using any other package managers @jjchan121? Are there any other environments on your path? Any other possible sources for where HDF5 is coming from? MATLAB?

**Comment by jjchan121** [comment]
@jakirkham Thanks.
Except the default Python (2.7), I only use Ananconda as package manager.

Previously I have an old hdf5 by homebrew but I have uninstalled it before installing the Ananconda.
I don't have Matlab but I have Mathematica 10 that has a HDF5 feature.

**Comment by jjchan121** [comment]
@jakirkham @kmuehlbauer Many thanks for your help! I have a very old hdf5 installed /usr/local/hdf5 and also my .bashrc export it to DYLD_LIBRARY_PATH and now I commented it out.

It fixed the issue. Issue is closed. Many thanks!

**Comment by jakirkham** [comment]
> Except the default Python (2.7), I only use Ananconda as package manager.

Sure, was just trying to be thorough.

> Mathematica 10 that has a HDF5 feature.

Interesting, good to know. Off topic, but do you know what this is for?

> I have a very old hdf5 installed /usr/local/hdf5 and also my .bashrc export it to DYLD_LIBRARY_PATH and now I commented it out.
> It fixed the issue.

Great! Glad to hear things are working for you again. :)

**Comment by jjchan121** [comment]
@jakirkham 
Interesting, good to know. Off topic, but do you know what this is for?
> It is able to open and save h5 file. http://reference.wolfram.com/language/ref/format/HDF5.html.en

**Comment by jakirkham** [comment]
Cool. Thanks for the info.

**Comment by alimahmoudi29** [comment]
**I received the following error:** 
```
Traceback (most recent call last):
  File "/anaconda3/bin/mspms", line 4, in <module>
    import msprime.cli
  File "/anaconda3/lib/python3.6/site-packages/msprime/__init__.py", line 26, in <module>
    from _msprime import FORWARD  # NOQA
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/_msprime.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/_msprime.cpython-36m-darwin.so
  Reason: image not found
```

**I fixed the issue by 
mv libhdf5.101.dylib libhdf5.10.dylib**  in directory **/usr/local/lib** .

**Comment by jakirkham** [comment]
That doesn't appear related to the `h5py` library @alimahmoudi29, but the `msprime` package. Could you please raise an issue on that feedstock instead? Also be sure to include a package listing so the maintainers can try to reproduce your issue. Thanks.

**Comment by jeromekelleher** [comment]
Hi @alimahmoudi29, this problem was caused by ``msprime``. The packages for ``msprime`` have been updated, and should be compatible now. Can you please check if it works for you now? If not, please open an issue at https://github.com/conda-forge/msprime-feedstock.

**Comment by serjtroshin** [comment]
`sudo install_name_tool -change "@rpath/libhdf5.10.dylib" "/Users/istar/anaconda/lib/libhdf5.10.dylib" /usr/local/lib/libarmadillo.8.dylib`
it helped me
