### ISSUE TITLE
Rerender with HDF5 1.10.3

### ISSUE THREAD

**Issue by xylar** [conda-forge/h5py-feedstock#41]
Is there a reason that h5py cannot be built with hdf5 1.10.3?  If it can be, I would be happy to submit at PR for this but I want to be clear if I should change 1.10.2 to 1.10.3 or just remove the pinning of the hdf5 version.

Background: I'm finding it very hard to create environments with the latest version of several packages (netcdf4, xarray, etc.) because of inconsistent hdf5 versions, and h5py is one critical bottleneck.

**Comment by xylar** [comment]
It looks from #42 like it's not going to be as easy as just rebuilding with hdf5 1.10.3, since 2 tests are failing:
```
running run_test.py
.....................................................x.........................s.........................................x....................................s...s......ss......................ss..................................................................E..................sss................................................................x....x.........................x......x........................................E........ssss.....s............
======================================================================
ERROR: test_exc (h5py.tests.old.test_group.TestLen)
len() on closed group gives ValueError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/h5py_1540117754725/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/site-packages/h5py/tests/old/test_group.py", line 302, in test_exc
    len(self.f)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/conda/feedstock_root/build_artifacts/h5py_1540117754725/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/site-packages/h5py/_hl/group.py", line 318, in __len__
    return self.id.get_num_objs()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5g.pyx", line 331, in h5py.h5g.GroupID.get_num_objs
TypeError: Not a location id (invalid object ID)
```

This seems to be the case across a number of platforms.

**Comment by xylar** [comment]
If this issue is with h5py, and not the feedstock, I'm happy to open an issue there instead.

**Comment by kmuehlbauer** [comment]
@xylar Maybe related: https://github.com/conda-forge/h5py-feedstock/pull/33#issuecomment-423360989

**Comment by xylar** [comment]
@kmuehlbauer, thank for pointing this out.  Clearly, h5py isn't quite there yet...

**Comment by tacaswell** [comment]
@xylar Eyes on https://github.com/h5py/h5py/pull/1099 would be greatly appreciated.

**Comment by xylar** [comment]
@tacaswell, I appreciate the need for more eyes on that PR but I don't have much HDF5 expertise to offer.
