### ISSUE TITLE
trouble installing h5py from conda forge, ros3 driver

### ISSUE THREAD

**Issue by bendichter** [conda-forge/h5py-feedstock#97]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Hy devs. Thanks for your work on this. I'm having trouble installing h5py from conda forge. Here are the steps I am using:
```bash
$ conda create -n test_h5py python=3.8 -y
$ conda activate test_h5py
$ conda install -c conda-forge h5py -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/bendichter/opt/miniconda3/envs/ajile

  added / updated specs:
    - h5py


The following NEW packages will be INSTALLED:

  cached-property    conda-forge/noarch::cached-property-1.5.2-hd8ed1ab_1
  cached_property    conda-forge/noarch::cached_property-1.5.2-pyha770c72_1
  h5py               conda-forge/osx-64::h5py-3.3.0-nompi_py39h1bb8402_100
  hdf5               conda-forge/osx-64::hdf5-1.10.6-nompi_h3e39495_100
  libblas            conda-forge/osx-64::libblas-3.9.0-8_openblas
  libcblas           conda-forge/osx-64::libcblas-3.9.0-8_openblas
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-7_5_0_h1a10cd1_23
  libgfortran4       conda-forge/osx-64::libgfortran4-7.5.0-h1a10cd1_23
  liblapack          conda-forge/osx-64::liblapack-3.9.0-8_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.12-openmp_h63d9170_1
  llvm-openmp        conda-forge/osx-64::llvm-openmp-12.0.1-hda6cdc1_1
  numpy              conda-forge/osx-64::numpy-1.21.1-py39h7eed0ac_0
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2021.5.30-py39hecd~ --> conda-forge::certifi-2021.5.30-py39h6e9494a_0
  openssl              pkgs/main::openssl-1.1.1k-h9ed2024_0 --> conda-forge::openssl-1.1.1k-h0d85af4_0

$ python
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: dlopen(/Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so, 2): Symbol not found: _H5Pget_fapl_ros3
  Referenced from: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
  Expected in: /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/libhdf5.103.dylib
 in /Users/bendichter/opt/anaconda3/envs/test_h5py/lib/python3.7/site-packages/h5py/defs.cpython-37m-darwin.so
```

I want to use the ros3 driver, so I can't simply downgrade h5py to an earlier version that does not support ros3.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
ca-certificates           2021.7.5             hecd8cb5_1  
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.5.30        py38h50d1736_0    conda-forge
h5py                      3.3.0           nompi_py38h9a16e60_100    conda-forge
hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
libgfortran               4.0.0           7_5_0_h1a10cd1_23    conda-forge
libgfortran4              7.5.0               h1a10cd1_23    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
llvm-openmp               12.0.1               hda6cdc1_1    conda-forge
ncurses                   6.2                  h0a44026_1  
numpy                     1.21.1           py38had91d27_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pip                       21.2.2           py38hecd8cb5_0  
python                    3.8.11          h88f2d9e_0_cpython  
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  h9ed2024_0  
setuptools                52.0.0           py38hecd8cb5_0  
sqlite                    3.36.0               hce871da_0  
tk                        8.6.10               hb0a8c7a_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : ajile
    active env location : /Users/bendichter/opt/miniconda3/envs/ajile
            shell level : 2
       user config file : /Users/bendichter/.condarc
 populated config files : /Users/bendichter/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/bendichter/opt/miniconda3  (writable)
      conda av data dir : /Users/bendichter/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/bendichter/opt/miniconda3/pkgs
                          /Users/bendichter/.conda/pkgs
       envs directories : /Users/bendichter/opt/miniconda3/envs
                          /Users/bendichter/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Darwin/20.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by luiztauffer** [comment]
Similar problem here:
```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-757261028123> in <module>
----> 1 import pynwb
      2 from pynwb import NWBHDF5IO
      3 from nwbwidgets import nwb2widget
      4 import requests
      5 

/opt/conda/lib/python3.9/site-packages/pynwb/__init__.py in <module>
      6 from copy import deepcopy
      7 from warnings import warn
----> 8 import h5py
      9 
     10 from hdmf.spec import NamespaceCatalog

/opt/conda/lib/python3.9/site-packages/h5py/__init__.py in <module>
     54 # --- Public API --------------------------------------------------------------
     55 
---> 56 from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z, h5pl
     57 
     58 from ._hl import filters

ImportError: /opt/conda/lib/python3.9/site-packages/h5py/h5fd.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5FD_mpio_init
```

**Comment by ocefpaf** [comment]
@luiztauffer you issue is not the same. Please open a new bug report with the required info so we can help you.

@bendichter I tested it on Linux and it works but it can be a macOS only problem. I'll see if I can test on a macOS machine later today.

**Comment by hmaarrfk** [comment]
I have a feeling it is because you mixed and matched defaults + conda-forge
https://conda-forge.org/docs/user/transitioning_from_defaults/
please comment if it is still not resolved.
